realsense2_camera_node:
  ros__parameters:
    device_type: 'd435i'
    serial_no: ''
    usb_port_id: ''
    rosbag_filename: ''
    initial_reset: true

    filters: ''
    enable_sync: false

    enable_color: true
    color_width: 1280
    color_height: 720
    color_fps: 32.0
    color_frame_id: camera_color_frame
    color_optical_frame_id: camera_color_optical_frame
    color_qos: DEFAULT

    enable_depth: true
    depth_width: 1280
    depth_height: 720
    depth_fps: 15.0
    depth_frame_id: camera_depth_frame
    depth_optical_frame_id: camera_depth_optical_frame

    enable_accel: true
    accel_fps: 0.0
    accel_frame_id: camera_accel_frame
    accel_optical_frame_id: camera_accel_optical_frame

    enable_gyro: true
    gyro_fps: 0.0
    gyro_frame_id: camera_gyro_frame
    gyro_optical_frame_id: camera_gyro_optical_frame

    enable_pose: false

    enable_infra: false

    enable_infra1: false

    enable_infra2: false

    base_frame_id: camera_link
    odom_frame_id: odom

    align_depth: false

    unite_imu_method: 'linear_interpolation'

    clip_distance: -1.0

    linear_accel_cov: 0.01
    angular_velocity_cov: 0.01
    hold_back_imu_for_frames: false

    publish_tf: true
    tf_publish_rate: 0.0
    publish_odom_tf: true

    motion_module:
      enable_motion_correction: true
      frames_queue_size: 16
      global_time_enabled: true
